import { Gemstone, Product } from '@/types';

export const products: Product[] = [
    // AFFORDABLE CVD SILK ROPE COLLECTION (8 products)
    {
        id: 'cvd-rope-bracelet-001',
        name: 'Silk Rope Diamond Bracelet - Black',
        slug: 'silk-rope-diamond-bracelet-black',
        category: 'Unisex',
        type: 'Bracelet',
        collection: 'Affordable CVD Silk Rope',
        price: 1250,
        images: ['/images/products/rope-bracelet-black-1.jpg'],
        description: 'Elegant silk rope bracelet featuring 0.25ct CVD diamond centerpiece. Minimal gold, maximum impact. Perfect for everyday luxury.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 1.5,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.25,
                quantity: 1,
                placement: 'center',
                clarity: 'VS1',
            }],
            ropeColor: 'Black',
            ropeMaterial: 'Premium Silk Cord',
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Made-to-Order',
            sizes: ['16cm', '17cm', '18cm', '19cm'],
            customizable: true,
        },
        seo: {
            title: 'Silk Rope Diamond Bracelet | Affordable CVD Diamond Jewelry',
            description: 'Handcrafted silk rope bracelet with CVD diamond. Unique, customizable, and affordable luxury.',
            keywords: ['cvd diamond bracelet', 'silk rope jewelry', 'affordable diamond', 'lab grown diamond'],
        },
        featured: true,
        tags: ['cvd', 'rope', 'bracelet', 'everyday', 'bestseller'],
    },
    {
        id: 'cvd-rope-necklace-002',
        name: 'Silk Rope Diamond Necklace - Navy',
        slug: 'silk-rope-diamond-necklace-navy',
        category: 'For Her',
        type: 'Necklace',
        collection: 'Affordable CVD Silk Rope',
        price: 1680,
        images: ['/images/products/rope-necklace-navy-1.jpg'],
        description: 'Delicate navy silk cord necklace with 0.35ct CVD diamond pendant. Sophisticated simplicity.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 1.8,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.35,
                quantity: 1,
                placement: 'pendant',
                clarity: 'VVS2',
            }],
            ropeColor: 'Navy',
            ropeMaterial: 'Premium Silk Cord',
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Made-to-Order',
            sizes: ['40cm', '45cm', '50cm'],
            customizable: true,
        },
        seo: {
            title: 'Navy Silk Rope Diamond Necklace | CVD Diamond',
            description: 'Elegant rope necklace with lab-grown diamond. Customizable colors and lengths.',
            keywords: ['diamond necklace', 'cvd', 'silk rope', 'lab diamond'],
        },
        featured: true,
        tags: ['cvd', 'rope', 'necklace', 'her'],
    },
    {
        id: 'cvd-rope-ring-003',
        name: 'Minimalist Rope Ring - Emerald',
        slug: 'minimalist-rope-ring-emerald',
        category: 'For Him',
        type: 'Ring',
        collection: 'Affordable CVD Silk Rope',
        price: 980,
        images: ['/images/products/rope-ring-emerald-1.jpg'],
        description: 'Unique rope-accented ring with 0.15ct CVD diamond. Bold yet refined.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 3.2,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Princess',
                caratWeight: 0.15,
                quantity: 1,
                placement: 'center',
                clarity: 'VS2',
            }],
            ropeColor: 'Emerald',
            ropeMaterial: 'Silk Rope Detail',
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            sizes: ['US 7', 'US 8', 'US 9', 'US 10', 'US 11'],
            customizable: true,
        },
        seo: {
            title: 'Mens Rope Ring CVD Diamond | Unique Design',
            description: 'Handcrafted rope ring with lab-grown diamond. Customizable for men.',
            keywords: ['mens ring', 'cvd diamond', 'unique ring', 'rope design'],
        },
        tags: ['cvd', 'rope', 'ring', 'him', 'unique'],
    },
    {
        id: 'cvd-rope-bracelet-004',
        name: 'Double Silk Rope Bracelet - Burgundy',
        slug: 'double-silk-rope-bracelet-burgundy',
        category: 'For Her',
        type: 'Bracelet',
        collection: 'Affordable CVD Silk Rope',
        price: 1420,
        images: ['/images/products/rope-bracelet-burgundy-1.jpg'],
        description: 'Dual silk cord design with twin 0.18ct CVD diamonds. Elegant layered look.',
        materials: {
            metal: '18K Rose Gold',
            metalWeight: 1.4,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.18,
                quantity: 2,
                placement: 'dual',
                clarity: 'VS1',
            }],
            ropeColor: 'Burgundy',
            ropeMaterial: 'Premium Silk Cord',
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Made-to-Order',
            sizes: ['16cm', '17cm', '18cm'],
            customizable: true,
        },
        seo: {
            title: 'Burgundy Silk Rope Diamond Bracelet | CVD',
            description: 'Unique double-rope bracelet with CVD diamonds. Affordable luxury.',
            keywords: ['rope bracelet', 'cvd diamond', 'burgundy', 'womens'],
        },
        tags: ['cvd', 'rope', 'bracelet', 'her'],
    },
    {
        id: 'cvd-rope-earrings-005',
        name: 'Silk Drop Earrings - White',
        slug: 'silk-drop-earrings-white',
        category: 'For Her',
        type: 'Earrings',
        collection: 'Affordable CVD Silk Rope',
        price: 1580,
        images: ['/images/products/rope-earrings-white-1.jpg'],
        description: 'Graceful drop earrings with white silk detail and 0.30ct CVD diamonds.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 2.0,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.30,
                quantity: 2,
                placement: 'drop',
                clarity: 'VVS1',
            }],
            ropeColor: 'White',
            ropeMaterial: 'Premium Silk Cord',
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'White Silk Drop Earrings CVD Diamond',
            description: 'Elegant drop earrings with lab-grown diamonds and silk detail.',
            keywords: ['drop earrings', 'cvd diamond', 'silk', 'luxury'],
        },
        tags: ['cvd', 'rope', 'earrings', 'her'],
    },
    {
        id: 'cvd-rope-bracelet-006',
        name: 'Silk Rope Bracelet - Gold',
        slug: 'silk-rope-bracelet-gold',
        category: 'Unisex',
        type: 'Bracelet',
        collection: 'Affordable CVD Silk Rope',
        price: 1350,
        images: ['/images/products/rope-bracelet-gold-1.jpg'],
        description: 'Gold silk rope with 0.28ct CVD diamond. Timeless elegance.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 1.6,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.28,
                quantity: 1,
                placement: 'center',
                clarity: 'VS1',
            }],
            ropeColor: 'Gold',
            ropeMaterial: 'Premium Silk Cord',
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Made-to-Order',
            sizes: ['16cm', '17cm', '18cm', '19cm', '20cm'],
            customizable: true,
        },
        seo: {
            title: 'Gold Silk Rope Diamond Bracelet | Unisex',
            description: 'Versatile rope bracelet with CVD diamond for men and women.',
            keywords: ['unisex bracelet', 'cvd diamond', 'gold rope'],
        },
        tags: ['cvd', 'rope', 'bracelet', 'unisex', 'bestseller'],
    },
    {
        id: 'cvd-rope-pendant-007',
        name: 'Minimalist Pendant - Black Rope',
        slug: 'minimalist-pendant-black-rope',
        category: 'For Him',
        type: 'Pendant',
        collection: 'Affordable CVD Silk Rope',
        price: 1180,
        images: ['/images/products/rope-pendant-black-1.jpg'],
        description: 'Sleek black rope pendant with 0.20ct CVD diamond. Modern masculinity.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 2.5,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Princess',
                caratWeight: 0.20,
                quantity: 1,
                placement: 'center',
                clarity: 'VS2',
            }],
            ropeColor: 'Black',
            ropeMaterial: 'Premium Silk Cord',
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Mens Black Rope Diamond Pendant | CVD',
            description: 'Modern pendant with lab-grown diamond and black silk rope.',
            keywords: ['mens pendant', 'cvd diamond', 'black rope', 'minimalist'],
        },
        tags: ['cvd', 'rope', 'pendant', 'him'],
    },
    {
        id: 'cvd-rope-necklace-008',
        name: 'Layered Rope Necklace - Navy & Gold',
        slug: 'layered-rope-necklace-navy-gold',
        category: 'For Her',
        type: 'Necklace',
        collection: 'Affordable CVD Silk Rope',
        price: 1890,
        images: ['/images/products/rope-necklace-layered-1.jpg'],
        description: 'Dual-tone rope necklace with 0.40ct CVD diamonds. Statement piece.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 2.2,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.40,
                quantity: 1,
                placement: 'pendant',
                clarity: 'VVS2',
            }],
            ropeColor: 'Navy',
            ropeMaterial: 'Dual-tone Silk Cord',
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            sizes: ['42cm', '45cm', '50cm'],
            customizable: true,
        },
        seo: {
            title: 'Layered Rope Diamond Necklace | Unique CVD',
            description: 'Sophisticated dual-tone rope necklace with lab-grown diamond.',
            keywords: ['layered necklace', 'cvd diamond', 'rope jewelry'],
        },
        featured: true,
        tags: ['cvd', 'rope', 'necklace', 'her', 'statement'],
    },

    // NATURAL DIAMOND COLLECTION (10 products)
    {
        id: 'nat-ring-001',
        name: 'Classic Solitaire Engagement Ring',
        slug: 'classic-solitaire-engagement-ring',
        category: 'For Her',
        type: 'Ring',
        collection: 'Natural Diamonds',
        price: 8950,
        images: ['/images/products/nat-solitaire-1.jpg'],
        description: 'Timeless solitaire with 1.0ct natural diamond. Certified excellence.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 3.8,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 1.0,
                quantity: 1,
                placement: 'center',
                clarity: 'VVS1',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['US 5', 'US 6', 'US 7', 'US 8'],
            customizable: true,
        },
        seo: {
            title: 'Natural Diamond Solitaire Engagement Ring 1ct',
            description: 'Classic solitaire ring with certified natural diamond. Timeless design.',
            keywords: ['engagement ring', 'natural diamond', 'solitaire', '1 carat'],
        },
        featured: true,
        tags: ['natural', 'ring', 'engagement', 'her', 'premium'],
    },
    {
        id: 'nat-necklace-002',
        name: 'Halo Diamond Pendant',
        slug: 'halo-diamond-pendant',
        category: 'For Her',
        type: 'Pendant',
        collection: 'Natural Diamonds',
        price: 6750,
        images: ['/images/products/nat-halo-pendant-1.jpg'],
        description: 'Exquisite halo pendant featuring 0.75ct center diamond surrounded by smaller natural diamonds.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 4.2,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 0.75,
                quantity: 1,
                placement: 'center',
                clarity: 'VS1',
            }, {
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 0.35,
                quantity: 16,
                placement: 'halo',
                clarity: 'VS2',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Natural Diamond Halo Pendant | Premium Jewelry',
            description: 'Stunning halo pendant with natural diamonds. Handcrafted in 18K gold.',
            keywords: ['diamond pendant', 'halo', 'natural diamond', 'luxury'],
        },
        featured: true,
        tags: ['natural', 'pendant', 'necklace', 'her', 'halo'],
    },
    {
        id: 'nat-earrings-003',
        name: 'Diamond Stud Earrings',
        slug: 'diamond-stud-earrings',
        category: 'For Her',
        type: 'Earrings',
        collection: 'Natural Diamonds',
        price: 5280,
        images: ['/images/products/nat-studs-1.jpg'],
        description: 'Classic diamond studs, 0.50ct each. Perfect everyday elegance.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 1.8,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 0.50,
                quantity: 2,
                placement: 'stud',
                clarity: 'VVS2',
            }],
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            customizable: false,
        },
        seo: {
            title: 'Natural Diamond Stud Earrings 1ct Total',
            description: 'Classic diamond studs in 18K white gold. Certified natural diamonds.',
            keywords: ['diamond studs', 'natural diamond', 'earrings', 'classic'],
        },
        tags: ['natural', 'earrings', 'her', 'classic', 'bestseller'],
    },
    {
        id: 'nat-bracelet-004',
        name: 'Tennis Bracelet - Natural Diamonds',
        slug: 'tennis-bracelet-natural-diamonds',
        category: 'For Her',
        type: 'Bracelet',
        collection: 'Natural Diamonds',
        price: 12500,
        images: ['/images/products/nat-tennis-1.jpg'],
        description: 'Iconic tennis bracelet with 3.5ct total natural diamonds. Statement luxury.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 8.5,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 3.5,
                quantity: 42,
                clarity: 'VS1',
            }],
        },
        specifications: {
            leadTimeDays: 21,
            availability: 'Made-to-Order',
            sizes: ['17cm', '18cm', '19cm'],
            customizable: true,
        },
        seo: {
            title: 'Natural Diamond Tennis Bracelet 3.5ct',
            description: 'Luxury tennis bracelet with natural diamonds. Timeless elegance.',
            keywords: ['tennis bracelet', 'natural diamond', 'luxury bracelet'],
        },
        featured: true,
        tags: ['natural', 'bracelet', 'her', 'luxury', 'statement'],
    },
    {
        id: 'nat-ring-005',
        name: 'Three Stone Engagement Ring',
        slug: 'three-stone-engagement-ring',
        category: 'For Her',
        type: 'Ring',
        collection: 'Natural Diamonds',
        price: 10200,
        images: ['/images/products/nat-three-stone-1.jpg'],
        description: 'Symbolic three stone ring with 1.2ct center and 0.40ct side stones.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 4.5,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Oval',
                caratWeight: 1.2,
                quantity: 1,
                placement: 'center',
                clarity: 'VVS1',
            }, {
                type: 'Natural Diamond',
                shape: 'Pear',
                caratWeight: 0.40,
                quantity: 2,
                placement: 'side',
                clarity: 'VS1',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['US 5', 'US 6', 'US 7', 'US 8'],
            customizable: true,
        },
        seo: {
            title: 'Three Stone Natural Diamond Engagement Ring',
            description: 'Stunning three stone ring with oval center and pear sides. Natural diamonds.',
            keywords: ['three stone ring', 'engagement ring', 'natural diamond', 'oval'],
        },
        tags: ['natural', 'ring', 'engagement', 'her'],
    },
    {
        id: 'nat-mens-ring-006',
        name: 'Mens Diamond Signet Ring',
        slug: 'mens-diamond-signet-ring',
        category: 'For Him',
        type: 'Ring',
        collection: 'Natural Diamonds',
        price: 7850,
        images: ['/images/products/nat-mens-signet-1.jpg'],
        description: 'Bold signet ring with 0.65ct natural diamond. Masculine elegance.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 12.0,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Princess',
                caratWeight: 0.65,
                quantity: 1,
                placement: 'center',
                clarity: 'VS1',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['US 9', 'US 10', 'US 11', 'US 12'],
            customizable: true,
        },
        seo: {
            title: 'Mens Diamond Signet Ring Natural Diamond',
            description: 'Bold signet ring with natural diamond. Handcrafted for men.',
            keywords: ['mens ring', 'signet ring', 'natural diamond', 'luxury'],
        },
        tags: ['natural', 'ring', 'him', 'signet'],
    },
    {
        id: 'nat-necklace-007',
        name: 'Diamond Riviera Necklace',
        slug: 'diamond-riviera-necklace',
        category: 'For Her',
        type: 'Necklace',
        collection: 'Natural Diamonds',
        price: 18900,
        images: ['/images/products/nat-riviera-1.jpg'],
        description: 'Spectacular riviera necklace with 5.0ct total natural diamonds.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 15.0,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 5.0,
                quantity: 52,
                clarity: 'VS1',
            }],
        },
        specifications: {
            leadTimeDays: 28,
            availability: 'Made-to-Order',
            sizes: ['40cm', '42cm'],
            customizable: true,
        },
        seo: {
            title: 'Natural Diamond Riviera Necklace 5ct',
            description: 'Exquisite riviera necklace with natural diamonds. Ultimate luxury.',
            keywords: ['riviera necklace', 'diamond necklace', 'natural diamond', 'luxury'],
        },
        featured: true,
        tags: ['natural', 'necklace', 'her', 'luxury', 'statement'],
    },
    {
        id: 'nat-earrings-008',
        name: 'Diamond Drop Earrings',
        slug: 'diamond-drop-earrings',
        category: 'For Her',
        type: 'Earrings',
        collection: 'Natural Diamonds',
        price: 8650,
        images: ['/images/products/nat-drops-1.jpg'],
        description: 'Elegant drop earrings with 1.5ct total natural diamonds.',
        materials: {
            metal: '18K Rose Gold',
            metalWeight: 3.5,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Pear',
                caratWeight: 1.5,
                quantity: 2,
                placement: 'drop',
                clarity: 'VVS1',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Natural Diamond Drop Earrings Pear Shape',
            description: 'Stunning pear-shaped diamond drop earrings in rose gold.',
            keywords: ['drop earrings', 'pear diamond', 'natural diamond', 'luxury'],
        },
        tags: ['natural', 'earrings', 'her', 'elegant'],
    },
    {
        id: 'nat-band-009',
        name: 'Eternity Band - Natural Diamonds',
        slug: 'eternity-band-natural-diamonds',
        category: 'For Her',
        type: 'Ring',
        collection: 'Natural Diamonds',
        price: 4580,
        images: ['/images/products/nat-eternity-1.jpg'],
        description: 'Classic eternity band with 1.2ct total natural diamonds.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 3.2,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 1.2,
                quantity: 18,
                clarity: 'VS2',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['US 5', 'US 6', 'US 7', 'US 8'],
            customizable: false,
        },
        seo: {
            title: 'Natural Diamond Eternity Band Wedding Ring',
            description: 'Classic eternity band with natural diamonds. Perfect wedding band.',
            keywords: ['eternity band', 'wedding ring', 'natural diamond'],
        },
        tags: ['natural', 'ring', 'her', 'wedding'],
    },
    {
        id: 'nat-mens-bracelet-010',
        name: 'Mens Diamond Link Bracelet',
        slug: 'mens-diamond-link-bracelet',
        category: 'For Him',
        type: 'Bracelet',
        collection: 'Natural Diamonds',
        price: 9850,
        images: ['/images/products/nat-mens-link-1.jpg'],
        description: 'Bold link bracelet with 2.0ct total natural diamonds. Modern luxury.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 22.0,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 2.0,
                quantity: 28,
                clarity: 'VS1',
            }],
        },
        specifications: {
            leadTimeDays: 21,
            availability: 'Made-to-Order',
            sizes: ['20cm', '21cm', '22cm'],
            customizable: true,
        },
        seo: {
            title: 'Mens Diamond Link Bracelet Natural Diamonds',
            description: 'Heavy gold link bracelet with natural diamonds. Bold statement.',
            keywords: ['mens bracelet', 'diamond bracelet', 'link bracelet', 'luxury'],
        },
        tags: ['natural', 'bracelet', 'him', 'luxury'],
    },

    // PERSONALIZED / CUSTOM SHOWCASE (6 products)
    {
        id: 'custom-name-necklace-001',
        name: 'Custom Name Necklace - Diamond Accents',
        slug: 'custom-name-necklace-diamond-accents',
        category: 'For Her',
        type: 'Necklace',
        collection: 'Custom & Personalized',
        price: 2850,
        images: ['/images/products/custom-name-1.jpg'],
        description: 'Personalized name necklace with natural diamond accents. Your name, your style.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 5.5,
            stones: [{
                type: 'Natural Diamond',
                shape: 'Round',
                caratWeight: 0.15,
                quantity: 3,
                placement: 'accent',
                clarity: 'VS2',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Custom Name Necklace with Diamonds | Personalized',
            description: 'Handcrafted personalized name necklace with diamond accents.',
            keywords: ['custom necklace', 'name necklace', 'personalized jewelry'],
        },
        featured: true,
        tags: ['custom', 'necklace', 'her', 'personalized'],
    },
    {
        id: 'custom-initial-ring-002',
        name: 'Engraved Initial Ring',
        slug: 'engraved-initial-ring',
        category: 'Unisex',
        type: 'Ring',
        collection: 'Custom & Personalized',
        price: 1680,
        images: ['/images/products/custom-initial-1.jpg'],
        description: 'Sleek signet ring with custom initial engraving. Timeless personalization.',
        materials: {
            metal: '18K Rose Gold',
            metalWeight: 8.0,
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            sizes: ['US 6', 'US 7', 'US 8', 'US 9', 'US 10'],
            customizable: true,
        },
        seo: {
            title: 'Custom Initial Engraved Ring | Personalized Signet',
            description: 'Elegant signet ring with your initials. Handcrafted in 18K gold.',
            keywords: ['initial ring', 'custom ring', 'engraved jewelry', 'signet'],
        },
        tags: ['custom', 'ring', 'unisex', 'engraved'],
    },
    {
        id: 'custom-birthstone-bracelet-003',
        name: 'Family Birthstone Bracelet',
        slug: 'family-birthstone-bracelet',
        category: 'For Her',
        type: 'Bracelet',
        collection: 'Custom & Personalized',
        price: 3250,
        images: ['/images/products/custom-birthstone-1.jpg'],
        description: 'Personalized bracelet featuring family birthstones. Cherish your loved ones.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 6.5,
            stones: [{
                type: 'Gemstone',
                shape: 'Round',
                caratWeight: 0.50,
                quantity: 4,
                color: 'Various',
            }],
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['17cm', '18cm', '19cm'],
            customizable: true,
        },
        seo: {
            title: 'Custom Family Birthstone Bracelet | Personalized Gift',
            description: 'Meaningful bracelet with family birthstones. Perfect gift.',
            keywords: ['birthstone bracelet', 'family jewelry', 'custom bracelet'],
        },
        tags: ['custom', 'bracelet', 'her', 'birthstone', 'family'],
    },
    {
        id: 'custom-coordinates-pendant-004',
        name: 'GPS Coordinates Pendant',
        slug: 'gps-coordinates-pendant',
        category: 'Unisex',
        type: 'Pendant',
        collection: 'Custom & Personalized',
        price: 1980,
        images: ['/images/products/custom-coordinates-1.jpg'],
        description: 'Engrave your special place. Coordinates pendant in premium gold.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 4.0,
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Custom GPS Coordinates Pendant | Personalized Jewelry',
            description: 'Unique pendant with your special coordinates engraved.',
            keywords: ['coordinates pendant', 'custom pendant', 'personalized gift'],
        },
        tags: ['custom', 'pendant', 'unisex', 'coordinates'],
    },
    {
        id: 'custom-wedding-bands-005',
        name: 'Matching Wedding Bands - Custom Engraving',
        slug: 'matching-wedding-bands-custom-engraving',
        category: 'Unisex',
        type: 'Ring',
        collection: 'Custom & Personalized',
        price: 3600,
        images: ['/images/products/custom-wedding-bands-1.jpg'],
        description: 'Matching wedding bands with personalized inside engraving. Your love, your way.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 7.0,
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['US 5-12 (pair)'],
            customizable: true,
        },
        seo: {
            title: 'Custom Wedding Bands Matching Set | Engraved',
            description: 'Personalized matching wedding bands with custom engraving.',
            keywords: ['wedding bands', 'custom rings', 'matching bands', 'engraved'],
        },
        featured: true,
        tags: ['custom', 'ring', 'unisex', 'wedding'],
    },
    {
        id: 'custom-photo-locket-006',
        name: 'Diamond Photo Locket',
        slug: 'diamond-photo-locket',
        category: 'For Her',
        type: 'Pendant',
        collection: 'Custom & Personalized',
        price: 2450,
        images: ['/images/products/custom-locket-1.jpg'],
        description: 'Classic locket with diamond accent. Keep your memories close.',
        materials: {
            metal: '18K Rose Gold',
            metalWeight: 5.0,
            stones: [{
                type: 'CVD Diamond',
                shape: 'Round',
                caratWeight: 0.10,
                quantity: 1,
                placement: 'accent',
                clarity: 'VS1',
            }],
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Diamond Photo Locket | Custom Personalized Pendant',
            description: 'Elegant locket with diamond. Personalize with your photo.',
            keywords: ['photo locket', 'diamond locket', 'personalized pendant'],
        },
        tags: ['custom', 'pendant', 'her', 'locket'],
    },

    // GENERAL COLLECTION - FOR HER (3 products)
    {
        id: 'her-bracelet-001',
        name: 'Delicate Chain Bracelet',
        slug: 'delicate-chain-bracelet',
        category: 'For Her',
        type: 'Bracelet',
        collection: 'For Her',
        price: 980,
        images: ['/images/products/her-chain-bracelet-1.jpg'],
        description: 'Minimalist chain bracelet in 18K gold. Everyday elegance.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 2.8,
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Ready to Ship',
            sizes: ['17cm', '18cm'],
            customizable: false,
        },
        seo: {
            title: 'Delicate Gold Chain Bracelet for Women',
            description: 'Minimalist 18K gold chain bracelet. Timeless design.',
            keywords: ['gold bracelet', 'chain bracelet', 'womens jewelry'],
        },
        tags: ['her', 'bracelet', 'gold', 'minimalist'],
    },
    {
        id: 'her-earrings-002',
        name: 'Gold Hoop Earrings',
        slug: 'gold-hoop-earrings',
        category: 'For Her',
        type: 'Earrings',
        collection: 'For Her',
        price: 1250,
        images: ['/images/products/her-hoops-1.jpg'],
        description: 'Classic gold hoops. Versatile and timeless.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 3.5,
        },
        specifications: {
            leadTimeDays: 7,
            availability: 'Ready to Ship',
            customizable: false,
        },
        seo: {
            title: '18K Gold Hoop Earrings Classic Design',
            description: 'Timeless gold hoop earrings for everyday wear.',
            keywords: ['gold hoops', 'hoop earrings', 'classic earrings'],
        },
        tags: ['her', 'earrings', 'gold', 'classic', 'bestseller'],
    },
    {
        id: 'her-ring-003',
        name: 'Stackable Ring Set',
        slug: 'stackable-ring-set',
        category: 'For Her',
        type: 'Ring',
        collection: 'For Her',
        price: 1650,
        images: ['/images/products/her-stackable-1.jpg'],
        description: 'Set of three stackable rings in mixed gold tones.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 4.2,
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            sizes: ['US 5', 'US 6', 'US 7', 'US 8'],
            customizable: false,
        },
        seo: {
            title: 'Stackable Ring Set Mixed Gold | For Her',
            description: 'Trendy stackable rings in 18K gold. Set of three.',
            keywords: ['stackable rings', 'ring set', 'gold rings'],
        },
        tags: ['her', 'ring', 'stackable', 'set'],
    },

    // GENERAL COLLECTION - FOR HIM (3 products)
    {
        id: 'him-bracelet-001',
        name: 'Mens Curb Chain Bracelet',
        slug: 'mens-curb-chain-bracelet',
        category: 'For Him',
        type: 'Bracelet',
        collection: 'For Him',
        price: 2850,
        images: ['/images/products/him-curb-bracelet-1.jpg'],
        description: 'Heavy curb chain bracelet. Bold and masculine.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 15.0,
        },
        specifications: {
            leadTimeDays: 14,
            availability: 'Made-to-Order',
            sizes: ['20cm', '21cm', '22cm'],
            customizable: false,
        },
        seo: {
            title: 'Mens Gold Curb Chain Bracelet Heavy',
            description: 'Bold 18K gold curb chain bracelet for men.',
            keywords: ['mens bracelet', 'curb chain', 'gold bracelet', 'heavy'],
        },
        tags: ['him', 'bracelet', 'gold', 'bold'],
    },
    {
        id: 'him-ring-002',
        name: 'Classic Mens Band',
        slug: 'classic-mens-band',
        category: 'For Him',
        type: 'Ring',
        collection: 'For Him',
        price: 1580,
        images: ['/images/products/him-band-1.jpg'],
        description: 'Timeless mens wedding band in 18K gold.',
        materials: {
            metal: '18K White Gold',
            metalWeight: 8.5,
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            sizes: ['US 9', 'US 10', 'US 11', 'US 12'],
            customizable: true,
        },
        seo: {
            title: 'Classic Mens Wedding Band 18K Gold',
            description: 'Traditional mens wedding band. Handcrafted quality.',
            keywords: ['mens wedding band', 'gold band', 'wedding ring'],
        },
        tags: ['him', 'ring', 'wedding', 'classic'],
    },
    {
        id: 'him-pendant-003',
        name: 'Mens Anchor Pendant',
        slug: 'mens-anchor-pendant',
        category: 'For Him',
        type: 'Pendant',
        collection: 'For Him',
        price: 1980,
        images: ['/images/products/him-anchor-1.jpg'],
        description: 'Bold anchor pendant in solid gold. Masculine nautical luxury with timeless style.',
        materials: {
            metal: '18K Yellow Gold',
            metalWeight: 6.5,
        },
        specifications: {
            leadTimeDays: 10,
            availability: 'Made-to-Order',
            customizable: true,
        },
        seo: {
            title: 'Mens Gold Anchor Pendant | Solid 18K Nautical Jewelry',
            description: 'Handcrafted anchor pendant in 18K gold for men. Nautical luxury with masculine style.',
            keywords: ['mens pendant', 'anchor pendant', 'gold anchor', 'nautical jewelry'],
        },
        tags: ['him', 'pendant', 'anchor', 'nautical'],
    },
];

export const gemstones: Gemstone[] = [
    {
        id: 'gem-sapphire-001',
        name: 'Blue Sapphire - 2.5ct',
        slug: 'blue-sapphire-2-5ct',
        type: 'Sapphire',
        shape: 'Oval',
        caratWeight: 2.5,
        color: 'Royal Blue',
        clarity: 'VVS',
        origin: 'Sri Lanka',
        price: 4500,
        images: ['/images/products/sapphire-blue-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-12345',
        description: 'Stunning royal blue sapphire from Sri Lanka. Exceptional clarity and color saturation.',
    },
    {
        id: 'gem-ruby-002',
        name: 'Pigeon Blood Ruby - 1.8ct',
        slug: 'pigeon-blood-ruby-1-8ct',
        type: 'Ruby',
        shape: 'Cushion',
        caratWeight: 1.8,
        color: 'Pigeon Blood Red',
        clarity: 'VVS',
        origin: 'Myanmar',
        price: 8900,
        images: ['/images/products/ruby-pigeon-1.jpg'],
        certified: true,
        certificateNumber: 'GRS-2024-67890',
        description: 'Rare pigeon blood ruby from Myanmar. Intense red with excellent clarity.',
    },
    {
        id: 'gem-emerald-003',
        name: 'Colombian Emerald - 3.0ct',
        slug: 'colombian-emerald-3-0ct',
        type: 'Emerald',
        shape: 'Emerald Cut',
        caratWeight: 3.0,
        color: 'Vivid Green',
        clarity: 'VS',
        origin: 'Colombia',
        price: 6750,
        images: ['/images/products/emerald-colombian-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-11223',
        description: 'Premium Colombian emerald with vivid green color and classic emerald cut.',
    },
    {
        id: 'gem-tanzanite-004',
        name: 'Tanzanite - 4.2ct',
        slug: 'tanzanite-4-2ct',
        type: 'Tanzanite',
        shape: 'Oval',
        caratWeight: 4.2,
        color: 'Violet-Blue',
        clarity: 'VVS',
        origin: 'Tanzania',
        price: 3200,
        images: ['/images/products/tanzanite-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-33445',
        description: 'Beautiful violet-blue tanzanite. Excellent size and clarity.',
    },
    {
        id: 'gem-aquamarine-005',
        name: 'Aquamarine - 5.5ct',
        slug: 'aquamarine-5-5ct',
        type: 'Aquamarine',
        shape: 'Emerald Cut',
        caratWeight: 5.5,
        color: 'Sky Blue',
        clarity: 'VVS',
        origin: 'Brazil',
        price: 2100,
        images: ['/images/products/aquamarine-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-55667',
        description: 'Large aquamarine with beautiful sky blue color. Exceptional clarity.',
    },
    {
        id: 'gem-tourmaline-006',
        name: 'Paraiba Tourmaline - 1.2ct',
        slug: 'paraiba-tourmaline-1-2ct',
        type: 'Tourmaline',
        shape: 'Oval',
        caratWeight: 1.2,
        color: 'Neon Blue',
        clarity: 'VVS',
        origin: 'Brazil',
        price: 12500,
        images: ['/images/products/tourmaline-paraiba-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-77889',
        description: 'Rare Paraiba tourmaline with electric neon blue color. Highly sought after.',
    },
    {
        id: 'gem-sapphire-pink-007',
        name: 'Pink Sapphire - 2.0ct',
        slug: 'pink-sapphire-2-0ct',
        type: 'Sapphire',
        shape: 'Cushion',
        caratWeight: 2.0,
        color: 'Vivid Pink',
        clarity: 'VVS',
        origin: 'Madagascar',
        price: 5200,
        images: ['/images/products/sapphire-pink-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-99001',
        description: 'Vibrant pink sapphire with excellent clarity. Perfect for custom designs.',
    },
    {
        id: 'gem-morganite-008',
        name: 'Morganite - 6.0ct',
        slug: 'morganite-6-0ct',
        type: 'Morganite',
        shape: 'Oval',
        caratWeight: 6.0,
        color: 'Peach Pink',
        clarity: 'VVS',
        origin: 'Madagascar',
        price: 1850,
        images: ['/images/products/morganite-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-12309',
        description: 'Large morganite with delicate peach-pink hue. Ideal for statement pieces.',
    },
    {
        id: 'gem-spinel-009',
        name: 'Red Spinel - 1.5ct',
        slug: 'red-spinel-1-5ct',
        type: 'Spinel',
        shape: 'Cushion',
        caratWeight: 1.5,
        color: 'Cherry Red',
        clarity: 'VVS',
        origin: 'Myanmar',
        price: 4200,
        images: ['/images/products/spinel-red-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-45678',
        description: 'Beautiful red spinel from Myanmar. Excellent alternative to ruby.',
    },
    {
        id: 'gem-alexandrite-010',
        name: 'Alexandrite - 1.0ct',
        slug: 'alexandrite-1-0ct',
        type: 'Alexandrite',
        shape: 'Round',
        caratWeight: 1.0,
        color: 'Color Change',
        clarity: 'VS',
        origin: 'Russia',
        price: 15000,
        images: ['/images/products/alexandrite-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-78901',
        description: 'Rare alexandrite with strong color change. Green in daylight, red in incandescent light.',
    },
    {
        id: 'gem-garnet-011',
        name: 'Tsavorite Garnet - 2.8ct',
        slug: 'tsavorite-garnet-2-8ct',
        type: 'Garnet',
        shape: 'Oval',
        caratWeight: 2.8,
        color: 'Vivid Green',
        clarity: 'VVS',
        origin: 'Kenya',
        price: 3400,
        images: ['/images/products/garnet-tsavorite-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-23456',
        description: 'Vibrant tsavorite garnet with exceptional green color.',
    },
    {
        id: 'gem-topaz-012',
        name: 'Imperial Topaz - 4.5ct',
        slug: 'imperial-topaz-4-5ct',
        type: 'Topaz',
        shape: 'Emerald Cut',
        caratWeight: 4.5,
        color: 'Golden Orange',
        clarity: 'VVS',
        origin: 'Brazil',
        price: 2600,
        images: ['/images/products/topaz-imperial-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-34567',
        description: 'Stunning imperial topaz with rich golden-orange hue.',
    },
    {
        id: 'gem-peridot-013',
        name: 'Peridot - 5.0ct',
        slug: 'peridot-5-0ct',
        type: 'Peridot',
        shape: 'Oval',
        caratWeight: 5.0,
        color: 'Lime Green',
        clarity: 'VVS',
        origin: 'Pakistan',
        price: 1200,
        images: ['/images/products/peridot-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-56789',
        description: 'Large peridot with vibrant lime green color. Excellent clarity.',
    },
    {
        id: 'gem-citrine-014',
        name: 'Madeira Citrine - 8.0ct',
        slug: 'madeira-citrine-8-0ct',
        type: 'Citrine',
        shape: 'Cushion',
        caratWeight: 8.0,
        color: 'Deep Orange',
        clarity: 'VVS',
        origin: 'Brazil',
        price: 950,
        images: ['/images/products/citrine-madeira-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-67890',
        description: 'Large madeira citrine with deep orange color. Beautiful and affordable.',
    },
    {
        id: 'gem-amethyst-015',
        name: 'Amethyst - 10.0ct',
        slug: 'amethyst-10-0ct',
        type: 'Amethyst',
        shape: 'Oval',
        caratWeight: 10.0,
        color: 'Deep Purple',
        clarity: 'VVS',
        origin: 'Uruguay',
        price: 850,
        images: ['/images/products/amethyst-1.jpg'],
        certified: true,
        certificateNumber: 'GIA-2024-89012',
        description: 'Impressive amethyst with deep purple color. Ideal for statement jewelry.',
    },
];

export function getProductBySlug(slug: string): Product | undefined {
    return products.find(p => p.slug === slug);
}

export function getProductById(id: string): Product | undefined {
    return products.find(p => p.id === id);
}

export function getProductsByCollection(collection: string): Product[] {
    return products.filter(p => p.collection === collection);
}

export function getProductsByCategory(category: string): Product[] {
    return products.filter(p => p.category === category);
}

export function getFeaturedProducts(): Product[] {
    return products.filter(p => p.featured);
}

export function getGemstoneBySlug(slug: string): Gemstone | undefined {
    return gemstones.find(g => g.slug === slug);
}
